default: cpsc2150/extendedTicTacToe/BoardPosition.java cpsc2150/extendedTicTacToe/GameBoard.java cpsc2150/extendedTicTacToe/GameScreen.java
	javac cpsc2150/extendedTicTacToe/BoardPosition.java cpsc2150/extendedTicTacToe/GameBoard.java cpsc2150/extendedTicTacToe/GameScreen.java

run: cpsc2150/extendedTicTacToe/BoardPosition.class cpsc2150/extendedTicTacToe/GameBoard.class cpsc2150/extendedTicTacToe/GameScreen.class
	java cpsc2150.extendedTicTacToe.GameScreen
	
clean: cpsc2150/extendedTicTacToe/BoardPosition.class cpsc2150/extendedTicTacToe/GameBoard.class cpsc2150/extendedTicTacToe/GameScreen.class
	rm cpsc2150/extendedTicTacToe/BoardPosition.class cpsc2150/extendedTicTacToe/GameBoard.class cpsc2150/extendedTicTacToe/GameScreen.class
